### ISSUE TITLE
Add Sample Datasets

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-erddap#1]
See https://github.com/clarity-h2020/csis/issues/12

**Comment by p-a-s-c-a-l** [comment]
All datasets must be manually registered in [datasets.xml](https://github.com/clarity-h2020/docker-erddap/blob/clarity/erddapConfig/datasets.xml). The scripts [GenerateDatasetsXml.sh](https://github.com/clarity-h2020/docker-erddap#running-errdap-cli-tools) can be used to generate a `<dataset>` xml snippet that can be added datasets.xml. However, this snippet is just a rough draft and needs to be changed. See [Working with the datasets.xml File](https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html). Therefore thorough knowledge of the respective dataset is needed to make it successfully available in ERDDAP. E.g. *GenerateDatasetsXml* asks for an ErdDap Dataset Type. For NetCDF files one can chose between EDDTableFromNcFiles, EDDTableFromNcCFFiles, EDDTableFromNccsvFiles, EDDTableFromMultidimNcFiles, EDDGridFromNcFiles, EDDGridFromNcFilesUnpacked. So the first question to be answered, do the sample NetCDF files contain gridded or tabular data? Another problem is, that *GenerateDatasetsXml* assumes that all files in a directory belong to the same dataset. So in case of \EURO-CORDEX\HazardMaps this will lead to the following exception:

```Java
datasets.xml error on line #227
While trying to load datasetID=RCP26_fdad_5ed8_ea58 (after 246 ms)
java.lang.RuntimeException: datasets.xml error on or before line #227: AxisVariable=time has tied values:
Duplicates at [0] and [1] = 33268.5
Duplicates at [1] and [2] = 33268.5
Duplicates at [3] and [4] = 44225.5
Duplicates at [4] and [5] = 44225.5
Duplicates at [6] and [7] = 55182.5
Duplicates at [7] and [8] = 55182.5
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:429)
 at gov.noaa.pfel.erddap.LoadDatasets.run(LoadDatasets.java:336)
Caused by: java.lang.RuntimeException: AxisVariable=time has tied values:
Duplicates at [0] and [1] = 33268.5
Duplicates at [1] and [2] = 33268.5
Duplicates at [3] and [4] = 44225.5
Duplicates at [4] and [5] = 44225.5
Duplicates at [6] and [7] = 55182.5
Duplicates at [7] and [8] = 55182.5

 at gov.noaa.pfel.erddap.variable.EDVGridAxis.<init>(EDVGridAxis.java:97)
 at gov.noaa.pfel.erddap.variable.EDVTimeStampGridAxis.<init>(EDVTimeStampGridAxis.java:89)
 at gov.noaa.pfel.erddap.variable.EDVTimeGridAxis.<init>(EDVTimeGridAxis.java:32)
 at gov.noaa.pfel.erddap.dataset.EDDGrid.makeAxisVariable(EDDGrid.java:375)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.<init>(EDDGridFromFiles.java:1073)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcLow.<init>(EDDGridFromNcLow.java:94)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromNcFiles.<init>(EDDGridFromNcFiles.java:99)
 at gov.noaa.pfel.erddap.dataset.EDDGridFromFiles.fromXml(EDDGridFromFiles.java:261)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:391)
 ... 1 more
```

**Comment by p-a-s-c-a-l** [comment]
Adding **20110101-20401231_extremelyhotdays_hazardmap_diff.nc** to ERDDAP results in the following WMS Map: 

![grafik](https://user-images.githubusercontent.com/1788226/44776474-714b8500-ab78-11e8-9502-665dd4bfb51a.png)

However, [Panoply](https://www.giss.nasa.gov/tools/panoply/) generates the following map from the same file:

![grafik](https://user-images.githubusercontent.com/1788226/44776203-d81c6e80-ab77-11e8-8efd-13477459a014.png)

The related xml snippet from datasets.xml generated by GenerateDatasetsXml.sh:

```xml
<axisVariable>
        <sourceName>y</sourceName>
        <destinationName>latitude</destinationName>
        <!-- sourceAttributes>
        </sourceAttributes -->
        <addAttributes>
            <att name="ioos_category">Location</att>
            <att name="long_name">Latitude</att>
            <att name="source_name">y</att>
            <att name="standard_name">latitude</att>
            <att name="units">degrees_north</att>
        </addAttributes>
    </axisVariable>
    <axisVariable>
        <sourceName>x</sourceName>
        <destinationName>longitude</destinationName>
        <!-- sourceAttributes>
        </sourceAttributes -->
        <addAttributes>
            <att name="ioos_category">Location</att>
            <att name="long_name">Longitude</att>
            <att name="source_name">x</att>
            <att name="standard_name">longitude</att>
            <att name="units">degrees_east</att>
        </addAttributes>
    </axisVariable>
```
Apparently degrees_north and degrees_east expected lat/lon values within -180 to 180, or 0 to 360, but the values for x and y in **20110101-20401231_extremelyhotdays_hazardmap_diff.nc** range from 0 - 423.

**Comment by p-a-s-c-a-l** [comment]
Setting up a WMS for **/MUKLIMO_3/Linz_number_of_summerdays_1981-2010.nc** fails because coordinates are expressed in meters and EPSG:3035 (ETRS89, LAEA) while ERDDAP  expects degrees_north and degrees_east.

**Comment by p-a-s-c-a-l** [comment]
HazardData in NetCDF is now transformed by METEOGRID and made available by via GeoServer. See also https://github.com/clarity-h2020/data-package/issues/8
